# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiDialogLog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogLog(object):
    def setupUi(self, DialogLog):
        DialogLog.setObjectName("DialogLog")
        DialogLog.resize(399, 382)
        self.scrollArea = QtWidgets.QScrollArea(DialogLog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 381, 361))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 379, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.etLog = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.etLog.setGeometry(QtCore.QRect(0, 0, 381, 361))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.etLog.setFont(font)
        self.etLog.setToolTip("")
        self.etLog.setStatusTip("")
        self.etLog.setWhatsThis("")
        self.etLog.setAccessibleName("")
        self.etLog.setAccessibleDescription("")
        self.etLog.setAutoFillBackground(False)
        self.etLog.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.etLog.setObjectName("etLog")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(DialogLog)
        QtCore.QMetaObject.connectSlotsByName(DialogLog)

    def retranslateUi(self, DialogLog):
        _translate = QtCore.QCoreApplication.translate
        DialogLog.setWindowTitle(_translate("DialogLog", "Dialog"))
        self.etLog.setPlainText(_translate("DialogLog", "ejemplo\n"
"texto\n"
"varias lineas\n"
"asd"))
