# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiDialogCalendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogCalendar(object):
    def setupUi(self, DialogCalendar):
        DialogCalendar.setObjectName("DialogCalendar")
        DialogCalendar.resize(400, 264)
        self.calendarWidget = QtWidgets.QCalendarWidget(DialogCalendar)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 0, 401, 261))
        self.calendarWidget.setObjectName("calendarWidget")

        self.retranslateUi(DialogCalendar)
        QtCore.QMetaObject.connectSlotsByName(DialogCalendar)

    def retranslateUi(self, DialogCalendar):
        _translate = QtCore.QCoreApplication.translate
        DialogCalendar.setWindowTitle(_translate("DialogCalendar", "Calendario"))
